name = "ChanVese"
uuid = "5a218058-8af7-4c90-a059-51daa47df457"
authors = ["Dale-Black <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
DistanceTransforms = "71182807-4d06-4237-8dd0-bdafe4d097e2"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
TestSetExtensions = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
